name: flash-api-docs
static_sites:
- name: flash-api-docs
  github:
    repo: YOUR_GITHUB_REPO
    branch: main
    deploy_on_push: true
  source_dir: public
  output_dir: /
  index_document: index.html
  error_document: index.html
  routes:
  - path: /
  environments:
  - name: production
    domain:
      name: docs.flashapp.me
      type: PRIMARY
    envs:
    - key: NODE_ENV
      value: production