name: Build and Deploy Flash API Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Fetch schema and build documentation
        run: npm run build
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: site-build
          path: public/
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: site-build
          path: public
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Deploy to DigitalOcean App Platform
        run: |
          # Create tar of the public directory
          tar -czf deploy.tar.gz -C public .
          
          # Deploy to DigitalOcean App Platform
          # Replace APP_ID with your actual DigitalOcean App ID
          doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }} --wait --format ID

      - name: Deployment Summary
        run: |
          echo "✅ Flash API Documentation has been successfully deployed to DigitalOcean!"
          echo "🔗 Live URL: https://flash-api-docs.${GITHUB_REF_NAME/main/flashapp.me}"